[tool.poetry]
name = "docs-llm-scraper"
version = "0.1.0"
description = "A CLI that crawls documentation sites and outputs an LLM-ready package for RAG"
authors = ["ThinkMark Team"]
readme = "README.md"
packages = [{include = "docs_llm_scraper"}]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
scrapy = "^2.8.0"
beautifulsoup4 = "^4.12.2"
markdownify = "^0.11.6"
tiktoken = "^0.5.1"
typer = "^0.9.0"
python-slugify = "^8.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
ruff = "^0.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
docs-llm-scraper = "docs_llm_scraper.cli:app"

[tool.ruff]
line-length = 100
target-version = "py311"
